### ISSUE TITLE
Excessive login issue

### ISSUE THREAD

**Issue by jonathantidwell** [rsnodgrass/hass-adtpulse#10]
I received a phone call from ADT themselves this morning informing me they disabled my account because of excessive logins. I checked, and two things occurred: my Hassio instance was locked up, and the logs on ADT Pulse's [history page](https://portal.adtpulse.com/myhome/20.0.0-221/history/history.jsp) show thousands of the same message, hundreds of time in one minute.

**Today 8:55 AM** - User **XXX** accessed this site via Web Portal (XXX.XXX.XXX.XXX).

Same message, many scrollbar lengths down.

I've seen some discussion about this on the [forums](https://community.home-assistant.io/t/adt-pulse-integration/10160/252), but wanted to add more data. I can provide any logs/configurations on my end if needed.

For what it's worth, ended up speaking with ADT's "IT department" to get the account unlocked and they expressed willingness on their side to help build something more official for integrations like this. The guy in question mentioned Home Assistant by name. Not sure if it was just small-talk.

**Comment by rsnodgrass** [comment]
Would be curious what specific query is causing an issue with ADT's systems, then we could update the client to either call less frequently, or cache some data, or perhaps alter the way the calls work.

If anyone else gets a call from the IT department, please get their contact email.

**Comment by rsnodgrass** [comment]
Also, someone should add exponential backoff to stop repeatedly trying to login.

https://pypi.org/project/backoff/

If nobody else gets to it, I'll try to investigate when I get some free time.

**Comment by rsnodgrass** [comment]
Released 0.1.5 which changed the default scan interval to 60 seconds. Users can then override to lower values if they want faster checks.
