### ISSUE TITLE
Component error:  adtpulse - Integration 'adtpulse' not found.

### ISSUE THREAD

**Issue by Redebo** [rsnodgrass/hass-adtpulse#13]
Updated to CORE 2021.6.0.  HACS is v1.12.4.  Adt pulse is v 0.17.

HA will not allow a restart after CORE update to 6.0 stating, "Component error:  adtpulse - Integration 'adtpulse' not found.

Has been working for months prior to release w/ no issue.

Yaml config file shows:
adtpulse:
  username: **login email addy**
  password: **correct password**

Log details:
Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/__init__.py:518
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 2:13:53 PM (2 occurrences)
Last logged: 2:16:51 PM

[140487396126928] The system cannot restart because the configuration is not valid: Component error: adtpulse - Integration 'adtpulse' not found.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 518, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Component error: adtpulse - Integration 'adtpulse' not found.

**Comment by HooverG** [comment]
Got the same error. There is no version in the manifest so the integration doesn't load. (requirement starting from HA 2021.6.0.)
Go to HACS and Reinstall ADTPulse on master instead of 0.1.7.
This solution should be temporary. Hopefully @rsnodgrass will package a 0.1.8 with the updated manifest.
Hope this helps.

**Comment by Redebo** [comment]
> Got the same error. There is no version in the manifest so the integration doesn't load. (requirement starting from HA 2021.6.0.)
> Go to HACS and Reinstall ADTPulse on master instead of 0.1.7.
> This solution should be temporary. Hopefully @rsnodgrass will package a 0.1.8 with the updated manifest.
> Hope this helps.

This fixed the issue (temporarily)!  Thanks a ton @HooverG

**Comment by rsnodgrass** [comment]
0.1.8 released

**Comment by Redebo** [comment]
> 0.1.8 released

Now THAT is service!  Thank you @rsnodgrass.

**Comment by drittzz** [comment]
Thanks for updating the package. I sent you a few coffees. :D
