### ISSUE TITLE
Error Codes from ADT Pulse 

### ISSUE THREAD

**Issue by prrandy** [rsnodgrass/hass-adtpulse#14]
I keep receiving these errors from my ADT Pulse integration. Any idea what they mean? Thanks in advance!

ERROR 1

Logger: pyadtpulse.site
Source: /usr/local/lib/python3.9/site-packages/pyadtpulse/site.py:85
First occurred: 10:53:28 AM (4 occurrences)
Last logged: 6:58:57 PM

Failed updating ADT Pulse alarm NAME Home to off (http=500)

ERROR 2

Logger: pyadtpulse
Source: /usr/local/lib/python3.9/site-packages/pyadtpulse/__init__.py:131
First occurred: 2:48:50 AM (15519 occurrences)
Last logged: 6:58:57 PM

ADT Pulse response (200): <div class="p_signinWarning" id="warnMsgContents">Sign In unsuccessful.<br/>Try again. Check your Caps Lock key.</div> 200
ADT Pulse response (429): None 429
ADT Pulse response (500): None 500

**Comment by rsnodgrass** [comment]
This is key:

```
Sign In unsuccessful.
Try again. Check your Caps Lock key.
```

Your password is incorrect *OR* ADT has blocked you (if you set your refresh interval too high I've heard they may block individual users).

**Comment by prrandy** [comment]
My login info is correct. Where can I change the refresh interval?

**Comment by rsnodgrass** [comment]
If you haven't changed it then the refresh interval should be fine...in the past some people have dialed it down to be super fast (so they detect motion alerts faster), but it caused problems with ADT's service so they got locked out.

Sorry I have no other suggestions.  Appears there is some authentication issue based on the log statements.

**Comment by prrandy** [comment]
Yea, that bit was obvious, but I haven't changed my password or messed with
the ADT account since I installed the add-on. So I reinstalled it and it
seems to have solved the issue for now.

*Randy Rivero*
*M.B.A. - Loyola University New Orleans*
*B.S. in Music Industry Studies - Loyola University New Orleans*
*Recording & Live Sound Technician / Entrepreneur*
*Email: ***@***.*** ***@***.***>*
*Phone: 863.303.6693*

**Comment by prrandy** [comment]
Yea, that bit was obvious, but I haven't changed my password or messed with the ADT account since I installed the add-on. So I reinstalled it and it seems to have solved the issue for now.

**Comment by rsnodgrass** [comment]
ADT Pulse added 2FA (two factor authentication) in the last few days supposedly, and accounts setup with 2FA will not work with this integration.  Not sure if that may be the issue for your account?  My Home Assistant that has ADT Pulse is not online right now for other reasons, so I cannot test.

**Comment by prrandy** [comment]
Ever since ADT pulse forced the users to sign up for 2FA,, the integration gas been broken. Are there any plans to make this integration work with 2FA?

**Comment by sbabcock23** [comment]
Please look at issue #7. There is more discussion on this and a potential workaround. I've also proposed an update that allows a user to pass a saved device.
