### ISSUE TITLE
Polling Interval

### ISSUE THREAD

**Issue by myopenflixr** [rsnodgrass/hass-adtpulse#18]
Hi,

I have successfully connected the ADT Pulse integration, but all of my sensors seem to take anywhere between 15-45 seconds to update.

Is there a way to get the sensors to update quicker? I have automations based on the sensors, and it takes quite a while to "trigger" them. 

Thanks,
Mike

**Comment by rsnodgrass** [comment]
You can adjust refresh_interval...but I suspect if you poll more frequently
ADT may lock your account since it consumes resources on their servers.
That is why the interval was raised, to be respectful to ADT.

**Comment by myopenflixr** [comment]
@rsnodgrass Thank you for the reply. I understand your decision to make the change.

However, If I wanted to make a change to the polling, where would I configure this and what is the command? I was thinking something on the lines of maybe 10 seconds.

**Comment by rsnodgrass** [comment]
I believe:

adtpulse:
  scan_interval: 10
