### ISSUE TITLE
Zones Not Updating in HA

### ISSUE THREAD

**Issue by rikan45** [rsnodgrass/hass-adtpulse#19]
Having an issue where most of the zones in my ADT setup are being updated in HA via this integration but a few zones either never update or only update intermittently several hours/days after an event occurs. The zone sensors that don't update in HA's logbook have corresponding entries in ADT's portal for the same time period. My two activity sensors are always updated but a few of the door sensors are out of sync with ADT. Any idea what might be causing this? In reviewing the logs, I see the following messages:

Logger: pyadtpulse
Source: /usr/local/lib/python3.9/site-packages/pyadtpulse/__init__.py:158
First occurred: 6:14:26 PM (1 occurrences)
Last logged: 6:14:26 PM
Unexpected sync check format (\d+[-]\d+[-]\d+), forcing re-auth

and also:

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549
First occurred: 4:32:27 PM (1 occurrences)
Last logged: 4:32:27 PM

Entity alarm_control_panel.adt_manmadhan_home (<class 'custom_components.adtpulse.alarm_control_panel.ADTPulseAlarm'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by rsnodgrass** [comment]
Closing old issues after major update to hass-adtpulse.
