### ISSUE TITLE
Error on Alarm Control Panel

### ISSUE THREAD

**Issue by drittzz** [rsnodgrass/hass-adtpulse#2]
File "/config/custom_components/adtpulse/alarm_control_panel.py", line 25, in setup_platform
    alarm_devices.append( ADTPulseAlarm(hass, adt_service, site) )
TypeError: Can't instantiate abstract class ADTPulseAlarm with abstract methods supported_features

**Comment by rsnodgrass** [comment]
This should be resolved in release 0.0.4, though I don't have an environment right now to test this in.
