### ISSUE TITLE
Installed ADT Pulse intergration with HACS. Can not locate any sensors or devices.

### ISSUE THREAD

**Issue by 007-DJ** [rsnodgrass/hass-adtpulse#20]
Following the install instructions:
Download this repository with HACS.
In ADT Pulse,
Created an additional "service" account user.  (workaround from @mrholshi) Followed ADT Invitation, set password. As instructed, not logging in to prevent F2A.
In the configuration.yaml 
default_config:
adtpulse:
  username: xxxxEmailAddress
  password: xxxxPassword

At this time, after several reboots of Home Assistant, I can not tell if login is successful or not, but I do not see any ADT sensors or ability to configure them.  I also attempted to capture "fingerprint" on may main account. the only thing similar in the capture was a cookie. But I had no idea of how to install it in HA as a device_id (Copy that value and use it for the device_id value in your configuration.yaml file) --- There is 1026 characters, shouldn't there be special formatting or all one line?

**Comment by 007-DJ** [comment]
I am convinced that F2A is automatically turned on now... Can anyone tell me how to put a HUGE fingerprint code in the configuration.yaml?  Shouldn't that be in the secrets.yaml file and even then... All one line?  what is the syntax?
Please don't refer me to the angry ADT helpless desk. Everyone knows they do not have "support".
If I figure the syntax, I should be able to go from there...

**Comment by sbabcock23** [comment]
Hi @007-DJ ,

The Readme has the instructions on how to get the device ID. You can copy and paste this value into your configuration.yaml. Its a single line configuration. a secrets file can be used as well if you want.

**Comment by 007-DJ** [comment]
Still having great difficulties... 2FA is definitely on... in my log, I am getting the following error:
2022-04-24 12:08:38 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration adtpulse which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-04-24 12:08:43 ERROR (SyncWorker_5) [pyadtpulse] ADT Pulse response (200): <div class="p_signinWarning" id="warnMsgContents">Sign In unsuccessful.<br/>Try again. Check your Caps Lock key.</div> 200
2022-04-24 12:08:43 ERROR (SyncWorker_0) [custom_components.adtpulse.binary_sensor] ADT's Pulse service returned NO sites: <PyADTPulse: xxxxxx@MyFairPoint.net>
2022-04-24 12:08:44 ERROR (SyncWorker_9) [custom_components.adtpulse.alarm_control_panel] ADT Pulse service failed to return sites: <PyADTPulse: xxxxxx@MyFairPoint.net>

Using Firefox, in the web developer tools recording, I do not see the page called "signin.jsp".  but i did locate something similar:
signin.jsp?e=ns&partner=adt  Under the security tab, i located finger prints. Definitely HEX and enclosed with quotation marks (as below).  and yes, the .... is in the file and just the code was changed to :##: 
 
Fingerprints	
SHA-256 Fingerprint:	"##:##:##:##:##:##:##:##:##:##…##:##:##:##:##:##:##:##:##:##"
SHA1 Fingerprint:	"##:##:##:##:##:##:##:##:##:##:##:##:##:##:##:##:##:##:##:##"

Neither of these look like what to expect from the readme, BUT in the Headers tab, I see a large code under the title 
Cookie: JSESSIONID#### >>> s_cc=true
(Approximately 100 characters, including either line feeds or enter marks.

So again for clarification... Is there a preferred browser to perform the capture to be in the configuration.yaml file
and do I include the quotation marks as discribed above?

Here is my current entry in the configuration.yaml  file:
default_config:
adtpulse:
  username: xxxxxx@MyFairPoint.net
  password: xxxxxxxxxxxxxxxxxxx
  device_id: "##:##:##:##:##:##:##:##:##:##…##:##:##:##:##:##:##:##:##:##"


Any suggestions or guidance would be greatly appreciated.

**Comment by rsnodgrass** [comment]
Closing old issues after major update to hass-adtpulse.
