### ISSUE TITLE
ADT Pulse integration with HACS suddenly fails sign in

### ISSUE THREAD

**Issue by kevintothecore** [rsnodgrass/hass-adtpulse#21]
After months of working with my login creds and device id, ADT Pulse integration with HACS keeps failing with this follow error log: 

Logger: pyadtpulse
Source: /usr/local/lib/python3.9/site-packages/pyadtpulse/__init__.py:133 
First occurred: 7:02:34 AM (2 occurrences) 
Last logged: 7:02:45 AM

ADT Pulse response (200): <div class="p_signinWarning" id="warnMsgContents">Sign In unsuccessful.<br/>Try again. Check your Caps Lock key.</div> 200

**Comment by rsnodgrass** [comment]
Closing old issues after major update to hass-adtpulse.
