### ISSUE TITLE
Slow startup causes async_setup_entry() to fail

### ISSUE THREAD

**Issue by rsnodgrass** [rsnodgrass/hass-adtpulse#27]
This is with the latest hass-adtpulse with the async updates.

```
Logger: homeassistant.config_entries
Source: custom_components/adtpulse/__init__.py:72
Integration: ADT Pulse ([documentation](https://github.com/rsnodgrass/hass-adtpulse/), [issues](https://github.com/rsnodgrass/hass-adtpulse/issues))
First occurred: 8:59:10 AM (1 occurrences)
Last logged: 8:59:10 AM

Error setting up entry ADT: rsnodgrass+hass@gmail.com for adtpulse
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/adtpulse/__init__.py", line 72, in async_setup_entry
    adtpulse = await hass.async_add_executor_job(PyADTPulse,entry.data[CONF_USERNAME], entry.data[CONF_PASSWORD], entry.data[CONF_FINGERPRINT], entry.data[CONF_HOSTNAME],ADT_DEFAULT_HTTP_HEADERS, None, True, polling, False)
asyncio.exceptions.CancelledError

**Comment by rsnodgrass** [comment]
What is graceful way to retry under this scenario? The hass-adtpulse never finished setup due to PyADTPulse asyncio op being cancelled.

**Comment by rlippmann** [comment]
Something is calling logout(), that's the only way the tasks will be cancelled.

I haven't been working on this because I can get async_setup_entry to even be called.  I manually wrote something to import the yaml, but haven't tested it.  It seems @sbabcock23  did it already, but I'm not sure if it will merge clean.

**Comment by rlippmann** [comment]
That’s odd since it’s the main config entry key. I’d seen that before when testing, but it seemed to go away when I reloaded the integration. 

@jimcj1301 have you also noticed that sensors stop being updated after about 4 hours?

**Comment by jimcj1301** [comment]
@rlippmann Yes, for me to get it to work again I have to remove the integration and start from scratch. After a bit, it stops working again. 

When it is working it's working great though. Let me know if there's anything you want me to test.

**Comment by rlippmann** [comment]
Hmm, it seems to be working reliably for me now. Wonder if it was a bug on ADT’s end?

**Comment by rsnodgrass** [comment]
ADT Pulse cloud services have definitely had issues with going offline in the last week. We had two different outages and could not even use ADT Pulse app.

**Comment by rlippmann** [comment]
@jimcj1301 since you have so many sensors, could you tell me how they show up on your system page? I just want to see the names of the device types.

i.e. 

![image](https://github.com/rsnodgrass/hass-adtpulse/assets/70883373/00046dd4-a8b0-4804-92b4-743e004e0362)

**Comment by jimcj1301** [comment]
@rlippmann System Page attached.

![image](https://github.com/rsnodgrass/hass-adtpulse/assets/1400418/b5114221-1a3f-4cbe-9ee7-a3642af5638b)

**Comment by jimcj1301** [comment]
Any updates on this issue?

**Comment by rlippmann** [comment]
Sorry, have been having personal issues, so haven’t gotten back to this for a little while. 

Is it this issue specifically, or something else?

**Comment by jimcj1301** [comment]
No Worries. I was just tinkering with a few issues in my HA and was curious. 

This is still the only current error I am getting. It kills the integration after a few hours it seems.

**Comment by rlippmann** [comment]
@jimcj1301 have you tried the integration recently?  It looks like ADT might have fixed the issue that kills the integration.

I've actually added some re-login logic to a new version I'm hoping to push soon.  Still debugging.

**Comment by rlippmann** [comment]
closing, appears fixed
