### ISSUE TITLE
Arm Home - Not working

### ISSUE THREAD

**Issue by drittzz** [rsnodgrass/hass-adtpulse#4]
Thanks for fixing it previously. I now can use Arm Away and Disarm. Although when attempting to use Arm Home I get the following error in the logs. 

Logger: frontend.js.latest.202002205
First occured: 11:43:57 AM (1 occurences)
Last logged: 11:43:57 AM

http://192.168.15.5:8123/frontend_latest/chunk.b5b99c32e8fe08e69155.js:3748:712 Uncaught TypeError: Cannot set property 'value' of null

**Comment by rsnodgrass** [comment]
I don't think Arm Home ever worked, as I only have Away and Disarm so this has never been tested.  If you see how to fix this, please submit a patch.  Thanks.

**Comment by dlyca307** [comment]
I put in a pull request on your pyadtpulse code that fixes this. The resolution was to change home to stay as that is the command ADT Pulse is using. Hope this gets rolled into your code base so others can use the arm home feature. Thanks!

**Comment by rsnodgrass** [comment]
Thank you for looking into this and resolved!  Your change has been merged and released.

**Comment by drittzz** [comment]
Since the merge, it broke.
