### ISSUE TITLE
Error after unknown timeout - Unexpected sync check format

### ISSUE THREAD

**Issue by jamesb2147** [rsnodgrass/hass-adtpulse#44]
Hey, for some reason I'm getting this error. I can start the HACS add-on, it works for some number of hours (2, perhaps, since that's my login timeout setting in the integration..?), then it stops working.

This is from the HA logs:
```
Logger: pyadtpulse
Source: runner.py:188
First occurred: 5:46:00 PM (233 occurrences)
Last logged: 7:56:54 PM

Unexpected sync check format (\d+[-]\d+[-]\d+), forcing re-auth
```
Any ideas on what could be causing that?

**Comment by rlippmann** [comment]
This hopefully should be fixed with 0.4.0
