### ISSUE TITLE
No Sensors

### ISSUE THREAD

**Issue by perfectionpenguin** [rsnodgrass/hass-adtpulse#7]
Have successfully installed via HACS and configured hass-adtpulse. I am able to arm/disarm via the control panel, however none of the sensors are generated as entities. The log contains a few errors along the lines of "Failed to load any zones from ADT Pulse service".

Failed to load any zones from ADT Pulse service
3:20:11 PM – custom_components/adtpulse/__init__.py (WARNING) - message first occurred at 3:20:05 PM and shows up 2 times
Error while setting up adtpulse platform for binary_sensor
3:19:59 PM – Binary sensor (ERROR)
Failed to load any zones from ADT Pulse service
3:19:59 PM – custom_components/adtpulse/binary_sensor.py (WARNING)
Failed to load any zones from ADT Pulse service
3:19:59 PM – custom_components/adtpulse/__init__.py (WARNING)

**Comment by rsnodgrass** [comment]
This is a known issue reported yesterday.  Will try to look at it in the
next few days, unless someone finds what the issue is.

**Comment by rsnodgrass** [comment]
ADT Pulse has remove/changed the service interface for querying zone status, so it doesn't matter which version you have installed currently.  I'll see if I can find a new service call which will return zones again.
